<?php
$data = array (
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '85',
    'name' => '家具',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '床',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '86',
    'name' => '床',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '铁艺床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '244',
    'name' => '铁艺床',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '板式床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '238',
    'name' => '板式床',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => '高低床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '248',
    'name' => '高低床',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '儿童床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '245',
    'name' => '儿童床',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => '皮床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '242',
    'name' => '皮床',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '布艺床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '239',
    'name' => '布艺床',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '实木床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '236',
    'name' => '实木床',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => '沙发床',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '249',
    'name' => '沙发床',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '柜子',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '90',
    'name' => '柜子',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '书柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '148',
    'name' => '书柜',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '餐边柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '155',
    'name' => '餐边柜',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '床头柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '152',
    'name' => '床头柜',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '衣柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '146',
    'name' => '衣柜',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '鞋柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '159',
    'name' => '鞋柜',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '电视柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => '电视柜',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '门厅柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '157',
    'name' => '门厅柜',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '床垫',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '床垫',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '棕榈床垫',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '183',
    'name' => '棕榈床垫',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '慢回弹记忆棉床垫',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '162',
    'name' => '慢回弹记忆棉床垫',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '椰棕床垫',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '180',
    'name' => '椰棕床垫',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => '乳胶床垫',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '181',
    'name' => '乳胶床垫',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '弹簧床垫',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '178',
    'name' => '弹簧床垫',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '架类',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => '架类',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => '梳妆台',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '202',
    'name' => '梳妆台',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => '置物架',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '206',
    'name' => '置物架',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => '书桌',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '203',
    'name' => '书桌',
  ),
  204 => 
  array (
    'cat_id' => '204',
    'cat_name' => '衣帽架',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '204',
    'name' => '衣帽架',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => '茶几',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '197',
    'name' => '茶几',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => '书架',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '205',
    'name' => '书架',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '沙发',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => '贵妃椅',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '192',
    'name' => '贵妃椅',
  ),
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => '皮沙发',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '189',
    'name' => '皮沙发',
  ),
  193 => 
  array (
    'cat_id' => '193',
    'cat_name' => '藤沙发',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '193',
    'name' => '藤沙发',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => '实木沙发',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '190',
    'name' => '实木沙发',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '布沙发',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '187',
    'name' => '布沙发',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => '懒人沙发',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '194',
    'name' => '懒人沙发',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '客厅家具',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '客厅家具',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '234',
    'name' => '餐椅',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => '餐桌',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '232',
    'name' => '餐桌',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => '餐桌椅',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '230',
    'name' => '餐桌椅',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '10',
    'has_children' => '14',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '护肤',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '护手霜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '护手霜',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '面膜',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '精油',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '精油',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '卸妆',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '洁面',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '洁面膏',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '洁面膏',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '洁面粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '洁面粉',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '洁面皂',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '洁面皂',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '洁面乳',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '凝胶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '凝胶',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '唇膏',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '唇膏',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '面霜',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '眼部护理',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '眼部护理',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '乳液',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '眼霜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '眼霜',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '爽肤水',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '原液',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '原液',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '测试',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '测试',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '精华',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '彩妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '20',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '彩妆',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '唇彩',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '唇彩',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '隔离',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '隔离',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '眼影',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '粉饼',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '粉饼',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '睫毛膏',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '睫毛膏',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '底妆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '底妆',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '粉底',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '粉底',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '香氛',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '香氛',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '香体露',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '香体露',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '女士香水',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '女士香水',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'Q 装',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => 'Q 装',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '中性香水',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '中性香水',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '男士香水',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '男士香水',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '装修服务',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 0,
    'id' => '100',
    'name' => '装修服务',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '局部施工',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '103',
    'name' => '局部施工',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '地毯清洗',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '地毯清洗',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '窗帘清洗',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '107',
    'name' => '窗帘清洗',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '安装',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '104',
    'name' => '安装',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '室内设计',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '101',
    'name' => '室内设计',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '地板保养',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '108',
    'name' => '地板保养',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '全屋保洁',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '105',
    'name' => '全屋保洁',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '监理',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '102',
    'name' => '监理',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => '配送',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '274',
    'name' => '配送',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '沙发保养',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '109',
    'name' => '沙发保养',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '搬家',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '106',
    'name' => '搬家',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '建材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '16',
    'goods_num' => 0,
    'level' => 0,
    'id' => '78',
    'name' => '建材',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '开关插座',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '79',
    'name' => '开关插座',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '插线板',
    'measure_unit' => '',
    'parent_id' => '79',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '插线板',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '断路器',
    'measure_unit' => '',
    'parent_id' => '79',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '130',
    'name' => '断路器',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '开关',
    'measure_unit' => '',
    'parent_id' => '79',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '127',
    'name' => '开关',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '防雷插座',
    'measure_unit' => '',
    'parent_id' => '79',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '131',
    'name' => '防雷插座',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '插座',
    'measure_unit' => '',
    'parent_id' => '79',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '128',
    'name' => '插座',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '厨卫电器',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '119',
    'name' => '厨卫电器',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '水槽',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '250',
    'name' => '水槽',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '小厨宝',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '257',
    'name' => '小厨宝',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '两件套',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '254',
    'name' => '两件套',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '烟机',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '251',
    'name' => '烟机',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '258',
    'name' => '热水器',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '三件套',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '255',
    'name' => '三件套',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => '灶具',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '252',
    'name' => '灶具',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => '集成灶',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '256',
    'name' => '集成灶',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => '消毒柜',
    'measure_unit' => '',
    'parent_id' => '119',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '253',
    'name' => '消毒柜',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '瓷砖',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '瓷砖',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => '马赛克',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '198',
    'name' => '马赛克',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => '釉面砖',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '195',
    'name' => '釉面砖',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => '瓷砖配件',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '201',
    'name' => '瓷砖配件',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => '玻化砖',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '196',
    'name' => '玻化砖',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => '天然石材',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '200',
    'name' => '天然石材',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '照明灯具',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '14',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '照明灯具',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '筒灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '筒灯',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '吸顶灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '132',
    'name' => '吸顶灯',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '其他灯饰',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '145',
    'name' => '其他灯饰',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '羊皮灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '142',
    'name' => '羊皮灯',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '镜前灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '139',
    'name' => '镜前灯',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '射灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '射灯',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '光源',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '133',
    'name' => '光源',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '落地灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '落地灯',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '水晶灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '水晶灯',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '壁灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '壁灯',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '台灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '台灯',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '小夜灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '144',
    'name' => '小夜灯',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '花灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '花灯',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => 'LED灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => 'LED灯',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '晾衣架',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '126',
    'name' => '晾衣架',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '防盗监控',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '123',
    'name' => '防盗监控',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '保险柜',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '273',
    'name' => '保险柜',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '门窗',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '120',
    'name' => '门窗',
  ),
  263 => 
  array (
    'cat_id' => '263',
    'cat_name' => '无框阳台',
    'measure_unit' => '',
    'parent_id' => '120',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '263',
    'name' => '无框阳台',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '防盗门',
    'measure_unit' => '',
    'parent_id' => '120',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '260',
    'name' => '防盗门',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => '阳光房',
    'measure_unit' => '',
    'parent_id' => '120',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '264',
    'name' => '阳光房',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => '隐形纱窗',
    'measure_unit' => '',
    'parent_id' => '120',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '261',
    'name' => '隐形纱窗',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => '防护窗',
    'measure_unit' => '',
    'parent_id' => '120',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '262',
    'name' => '防护窗',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => '木门',
    'measure_unit' => '',
    'parent_id' => '120',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '259',
    'name' => '木门',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '橱柜',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '橱柜',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => '人造石台面',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '212',
    'name' => '人造石台面',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => '烤漆橱柜',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '209',
    'name' => '烤漆橱柜',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => '石英石台面',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '213',
    'name' => '石英石台面',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => 'UV橱柜',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '210',
    'name' => 'UV橱柜',
  ),
  207 => 
  array (
    'cat_id' => '207',
    'cat_name' => '实木橱柜',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '207',
    'name' => '实木橱柜',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => '整体板橱柜',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '211',
    'name' => '整体板橱柜',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => '模压橱柜',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '208',
    'name' => '模压橱柜',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '移门衣柜',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => 0,
    'level' => 1,
    'id' => '117',
    'name' => '移门衣柜',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => '人造板移门',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '218',
    'name' => '人造板移门',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '刨花板衣柜',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '215',
    'name' => '刨花板衣柜',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => '衣柜储物篮',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '225',
    'name' => '衣柜储物篮',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '儿童房移门',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '222',
    'name' => '儿童房移门',
  ),
  219 => 
  array (
    'cat_id' => '219',
    'cat_name' => '皮革移门',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '219',
    'name' => '皮革移门',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => '平开门',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '216',
    'name' => '平开门',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '穿衣镜',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '226',
    'name' => '穿衣镜',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => '裤抽',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '223',
    'name' => '裤抽',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => '实木移门',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '220',
    'name' => '实木移门',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => '玻璃移门',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '217',
    'name' => '玻璃移门',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => '中纤板衣柜',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '214',
    'name' => '中纤板衣柜',
  ),
  224 => 
  array (
    'cat_id' => '224',
    'cat_name' => '衣通',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '224',
    'name' => '衣通',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '隔断门',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '221',
    'name' => '隔断门',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '卫浴',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '20',
    'goods_num' => 0,
    'level' => 1,
    'id' => '81',
    'name' => '卫浴',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '浴室柜',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '151',
    'name' => '浴室柜',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '座便器盖板',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '167',
    'name' => '座便器盖板',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '拖把池',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '177',
    'name' => '拖把池',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '浴缸',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 2,
    'id' => '158',
    'name' => '浴缸',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '普通浴缸',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '161',
    'name' => '普通浴缸',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '按摩浴缸',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '160',
    'name' => '按摩浴缸',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '角阀',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '174',
    'name' => '角阀',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '浴镜',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '171',
    'name' => '浴镜',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '浴缸龙头',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '168',
    'name' => '浴缸龙头',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '淋浴花洒',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => '淋浴花洒',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '立柱盆',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '165',
    'name' => '立柱盆',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => '花洒配件',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '176',
    'name' => '花洒配件',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '淋浴房',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '156',
    'name' => '淋浴房',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '地漏',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '175',
    'name' => '地漏',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '座便器',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '153',
    'name' => '座便器',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '洗衣机龙头',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '169',
    'name' => '洗衣机龙头',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '浴室五金',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '166',
    'name' => '浴室五金',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '实木浴桶',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '147',
    'name' => '实木浴桶',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '复古浴室柜',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '163',
    'name' => '复古浴室柜',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '软管',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '173',
    'name' => '软管',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '智能座便器',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '154',
    'name' => '智能座便器',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '面盆龙头',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '170',
    'name' => '面盆龙头',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '家用五金',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '124',
    'name' => '家用五金',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '窗帘',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '121',
    'name' => '窗帘',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => '纱帘',
    'measure_unit' => '',
    'parent_id' => '121',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '266',
    'name' => '纱帘',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => '布帘+纱帘',
    'measure_unit' => '',
    'parent_id' => '121',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '268',
    'name' => '布帘+纱帘',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => '布帘',
    'measure_unit' => '',
    'parent_id' => '121',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '265',
    'name' => '布帘',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '集成吊顶',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 1,
    'id' => '118',
    'name' => '集成吊顶',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => '凹凸板',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '231',
    'name' => '凹凸板',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '滚涂板',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '247',
    'name' => '滚涂板',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => '覆膜板',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '228',
    'name' => '覆膜板',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => '换气模块',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '241',
    'name' => '换气模块',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '复古板',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '235',
    'name' => '复古板',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => '氧化板',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '229',
    'name' => '氧化板',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => '艺术花片',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '233',
    'name' => '艺术花片',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '换气扇',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '246',
    'name' => '换气扇',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => '浴霸',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '227',
    'name' => '浴霸',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '组合电器',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '243',
    'name' => '组合电器',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => '取暖模块',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '240',
    'name' => '取暖模块',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => '照明模块',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '237',
    'name' => '照明模块',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '地板',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '地板',
  ),
  185 => 
  array (
    'cat_id' => '185',
    'cat_name' => '竹地板',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '185',
    'name' => '竹地板',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '实木复合地板',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '182',
    'name' => '实木复合地板',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '强化地板',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '179',
    'name' => '强化地板',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '进口地板',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '186',
    'name' => '进口地板',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '实木地板',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '184',
    'name' => '实木地板',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => '扣条',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '191',
    'name' => '扣条',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => '踢脚线',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '188',
    'name' => '踢脚线',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '工具专区',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '125',
    'name' => '工具专区',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '墙面装饰',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '122',
    'name' => '墙面装饰',
  ),
  270 => 
  array (
    'cat_id' => '270',
    'cat_name' => '油漆涂料',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '270',
    'name' => '油漆涂料',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '墙纸',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '272',
    'name' => '墙纸',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => '硅藻泥',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '269',
    'name' => '硅藻泥',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '家居饰品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '111',
    'name' => '家居饰品',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '炭雕',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '116',
    'name' => '炭雕',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '挂钟',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '挂钟',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => '仿真花',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '267',
    'name' => '仿真花',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '装饰画',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '114',
    'name' => '装饰画',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => '鱼缸',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '271',
    'name' => '鱼缸',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '墙贴',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '115',
    'name' => '墙贴',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '地毯',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '地毯',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '男士专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '62',
    'name' => '男士专区',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '乳液',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '66',
    'name' => '面霜',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '洁面',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '70',
    'name' => '精华',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '眼霜',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '67',
    'name' => '眼霜',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '男香',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => '男香',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '凝胶',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => '凝胶',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '65',
    'name' => '爽肤水',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '身体护理',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '瘦身',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '瘦身',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '50',
    'name' => '沐浴',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '手足护理',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '手足护理',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '身体乳',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '身体乳',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '洗发',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '保健品',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '保健品',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '脱毛',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '脱毛',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '护发',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '健康家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '92',
    'name' => '健康家居',
  ),
  282 => 
  array (
    'cat_id' => '282',
    'cat_name' => '空气检测',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '282',
    'name' => '空气检测',
  ),
  283 => 
  array (
    'cat_id' => '283',
    'cat_name' => '舒适冷暖',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '283',
    'name' => '舒适冷暖',
  ),
  285 => 
  array (
    'cat_id' => '285',
    'cat_name' => '地暖',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '285',
    'name' => '地暖',
  ),
  286 => 
  array (
    'cat_id' => '286',
    'cat_name' => '中央空调',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '286',
    'name' => '中央空调',
  ),
  278 => 
  array (
    'cat_id' => '278',
    'cat_name' => '净水处理',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '278',
    'name' => '净水处理',
  ),
  279 => 
  array (
    'cat_id' => '279',
    'cat_name' => '中央净水机',
    'measure_unit' => '',
    'parent_id' => '278',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '279',
    'name' => '中央净水机',
  ),
  280 => 
  array (
    'cat_id' => '280',
    'cat_name' => '软水机',
    'measure_unit' => '',
    'parent_id' => '278',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '280',
    'name' => '软水机',
  ),
  281 => 
  array (
    'cat_id' => '281',
    'cat_name' => '净水机',
    'measure_unit' => '',
    'parent_id' => '278',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '281',
    'name' => '净水机',
  ),
  288 => 
  array (
    'cat_id' => '288',
    'cat_name' => '垃圾处理器',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '288',
    'name' => '垃圾处理器',
  ),
  287 => 
  array (
    'cat_id' => '287',
    'cat_name' => '影音音响',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '287',
    'name' => '影音音响',
  ),
  275 => 
  array (
    'cat_id' => '275',
    'cat_name' => '空气净化',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '275',
    'name' => '空气净化',
  ),
  277 => 
  array (
    'cat_id' => '277',
    'cat_name' => '氧吧',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '277',
    'name' => '氧吧',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => '空气净化器',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '276',
    'name' => '空气净化器',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '美妆工具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '美妆工具',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '美容仪器',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '美容仪器',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '化妆刷',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '化妆刷',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '化妆棉',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '化妆棉',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '套装礼盒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '套装礼盒',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '美体套装',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '美体套装',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '香水+身体乳套装',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => '香水+身体乳套装',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '护发套装',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '护发套装',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '护肤套装',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '护肤套装',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '限时特卖',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '限时特卖',
  ),
);
?>