<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ecs_category`;");
E_C("CREATE TABLE `ecs_category` (
  `cat_id` smallint(5) unsigned NOT NULL auto_increment,
  `cat_name` varchar(90) NOT NULL default '',
  `keywords` varchar(255) NOT NULL default '',
  `cat_desc` varchar(255) NOT NULL default '',
  `parent_id` smallint(5) unsigned NOT NULL default '0',
  `sort_order` tinyint(1) unsigned NOT NULL default '50',
  `template_file` varchar(50) NOT NULL default '',
  `measure_unit` varchar(15) NOT NULL default '',
  `show_in_nav` tinyint(1) NOT NULL default '0',
  `style` varchar(150) NOT NULL,
  `is_show` tinyint(1) unsigned NOT NULL default '1',
  `grade` tinyint(4) NOT NULL default '0',
  `filter_attr` varchar(255) NOT NULL default '0',
  PRIMARY KEY  (`cat_id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=MyISAM AUTO_INCREMENT=289 DEFAULT CHARSET=utf8");
E_D("replace into `ecs_category` values('1','彩妆','','','0','20','','','1','','0','5','');");
E_D("replace into `ecs_category` values('26','面霜','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('25','爽肤水','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('24','面膜','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('6','护肤','','','0','10','','','0','','0','5','212,211,165');");
E_D("replace into `ecs_category` values('28','眼霜','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('27','护手霜','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('29','凝胶','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('12','香氛','','','0','30','','','1','','0','0','');");
E_D("replace into `ecs_category` values('20','限时特卖','','','0','100','','','0','','0','0','');");
E_D("replace into `ecs_category` values('22','洁面','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('23','乳液','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('16','身体护理','','','0','50','','','1','','0','0','');");
E_D("replace into `ecs_category` values('17','美妆工具','','','0','60','','','1','','0','0','');");
E_D("replace into `ecs_category` values('18','套装礼盒','','','0','70','','','0','','0','0','');");
E_D("replace into `ecs_category` values('30','精华','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('31','卸妆','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('32','眼部护理','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('33','原液','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('34','精油','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('35','唇膏','','','6','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('36','底妆','','','1','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('37','唇彩','','','1','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('38','眼影','','','1','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('39','睫毛膏','','','1','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('40','粉底','','','1','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('41','隔离','','','1','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('42','粉饼','','','1','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('43','男士香水','','','12','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('44','女士香水','','','12','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('45','Q 装','','','12','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('46','中性香水','','','12','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('47','香体露','','','12','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('48','洗发','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('49','护发','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('50','沐浴','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('51','身体乳','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('52','脱毛','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('53','瘦身','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('54','手足护理','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('55','化妆刷','','','17','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('56','化妆棉','','','17','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('57','美容仪器','','','17','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('58','护发套装','','','18','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('59','护肤套装','','','18','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('60','美体套装','','','18','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('61','香水+身体乳套装','','','18','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('62','男士专区','','','0','50','','','0','','0','0','');");
E_D("replace into `ecs_category` values('63','洁面','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('64','男香','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('65','爽肤水','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('66','面霜','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('67','眼霜','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('68','凝胶','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('69','乳液','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('70','精华','','','62','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('71','保健品','','','16','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('73','洁面乳','','','22','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('74','洁面膏','','','22','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('75','洁面粉','','','22','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('76','洁面皂','','','22','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('77','测试','','','33','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('78','建材','','','0','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('79','开关插座','','','78','0','','','0','','1','0','');");
E_D("replace into `ecs_category` values('80','照明灯具','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('81','卫浴','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('82','地板','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('83','瓷砖','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('84','橱柜','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('85','家具','','','0','1','','','0','','1','0','');");
E_D("replace into `ecs_category` values('86','床','','','85','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('87','床垫','','','85','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('88','沙发','','','85','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('89','客厅家具','','','85','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('90','柜子','','','85','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('91','架类','','','85','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('92','健康家居','','','0','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('277','氧吧','','','275','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('276','空气净化器','','','275','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('275','空气净化','','','92','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('279','中央净水机','','','278','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('278','净水处理','','','92','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('274','配送','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('100','装修服务','','','0','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('101','室内设计','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('102','监理','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('103','局部施工','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('104','安装','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('105','全屋保洁','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('106','搬家','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('107','窗帘清洗','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('108','地板保养','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('109','沙发保养','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('110','地毯清洗','','','100','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('111','家居饰品','','','0','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('112','地毯','','','111','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('113','挂钟','','','111','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('114','装饰画','','','111','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('115','墙贴','','','111','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('116','炭雕','','','111','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('117','移门衣柜','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('118','集成吊顶','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('119','厨卫电器','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('120','门窗','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('121','窗帘','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('122','墙面装饰','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('123','防盗监控','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('124','家用五金','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('125','工具专区','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('126','晾衣架','','','78','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('127','开关','','','79','50','','','0','','1','0','0');");
E_D("replace into `ecs_category` values('128','插座','','','79','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('129','插线板','','','79','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('130','断路器','','','79','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('131','防雷插座','','','79','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('132','吸顶灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('133','光源','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('134','台灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('135','筒灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('136','射灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('137','壁灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('138','LED灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('139','镜前灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('140','水晶灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('141','花灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('142','羊皮灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('143','落地灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('144','小夜灯','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('145','其他灯饰','','','80','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('146','衣柜','','','90','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('147','实木浴桶','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('148','书柜','','','90','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('149','淋浴花洒','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('150','电视柜','','','90','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('151','浴室柜','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('152','床头柜','','','90','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('153','座便器','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('154','智能座便器','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('155','餐边柜','','','90','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('156','淋浴房','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('157','门厅柜','','','90','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('158','浴缸','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('159','鞋柜','','','90','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('160','按摩浴缸','','','158','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('161','普通浴缸','','','158','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('162','慢回弹记忆棉床垫','','','87','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('163','复古浴室柜','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('177','拖把池','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('165','立柱盆','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('166','浴室五金','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('167','座便器盖板','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('168','浴缸龙头','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('169','洗衣机龙头','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('170','面盆龙头','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('171','浴镜','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('175','地漏','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('173','软管','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('174','角阀','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('176','花洒配件','','','81','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('178','弹簧床垫','','','87','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('179','强化地板','','','82','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('180','椰棕床垫','','','87','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('181','乳胶床垫','','','87','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('182','实木复合地板','','','82','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('183','棕榈床垫','','','87','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('184','实木地板','','','82','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('185','竹地板','','','82','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('186','进口地板','','','82','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('187','布沙发','','','88','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('188','踢脚线','','','82','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('189','皮沙发','','','88','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('190','实木沙发','','','88','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('191','扣条','','','82','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('192','贵妃椅','','','88','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('193','藤沙发','','','88','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('194','懒人沙发','','','88','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('195','釉面砖','','','83','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('196','玻化砖','','','83','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('197','茶几','','','91','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('198','马赛克','','','83','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('201','瓷砖配件','','','83','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('200','天然石材','','','83','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('202','梳妆台','','','91','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('203','书桌','','','91','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('204','衣帽架','','','91','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('205','书架','','','91','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('206','置物架','','','91','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('207','实木橱柜','','','84','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('208','模压橱柜','','','84','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('209','烤漆橱柜','','','84','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('210','UV橱柜','','','84','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('211','整体板橱柜','','','84','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('212','人造石台面','','','84','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('213','石英石台面','','','84','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('214','中纤板衣柜','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('215','刨花板衣柜','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('216','平开门','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('217','玻璃移门','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('218','人造板移门','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('219','皮革移门','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('220','实木移门','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('221','隔断门','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('222','儿童房移门','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('223','裤抽','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('224','衣通','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('225','衣柜储物篮','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('226','穿衣镜','','','117','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('227','浴霸','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('228','覆膜板','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('229','氧化板','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('230','餐桌椅','','','89','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('231','凹凸板','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('232','餐桌','','','89','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('233','艺术花片','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('234','餐椅','','','89','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('235','复古板','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('236','实木床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('237','照明模块','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('238','板式床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('239','布艺床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('240','取暖模块','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('241','换气模块','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('242','皮床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('243','组合电器','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('244','铁艺床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('245','儿童床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('246','换气扇','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('247','滚涂板','','','118','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('248','高低床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('249','沙发床','','','86','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('250','水槽','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('251','烟机','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('252','灶具','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('253','消毒柜','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('254','两件套','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('255','三件套','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('256','集成灶','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('257','小厨宝','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('258','热水器','','','119','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('259','木门','','','120','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('260','防盗门','','','120','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('261','隐形纱窗','','','120','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('262','防护窗','','','120','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('263','无框阳台','','','120','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('264','阳光房','','','120','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('265','布帘','','','121','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('266','纱帘','','','121','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('267','仿真花','','','111','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('268','布帘+纱帘','','','121','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('269','硅藻泥','','','122','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('270','油漆涂料','','','122','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('271','鱼缸','','','111','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('272','墙纸','','','122','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('273','保险柜','','','123','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('280','软水机','','','278','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('281','净水机','','','278','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('282','空气检测','','','92','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('283','舒适冷暖','','','92','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('287','影音音响','','','92','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('285','地暖','','','283','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('286','中央空调','','','283','50','','','0','','1','0','');");
E_D("replace into `ecs_category` values('288','垃圾处理器','','','92','50','','','0','','1','0','');");

require("../../inc/footer.php");
?>